"""Tests for scripts/validate_bucket_names.py."""

import json
import textwrap

import validate_bucket_names as vbn


# ---------------------------------------------------------------------------
# is_valid_bucket_name — convention: {prefix}-{12-digit-account}-{region}-an
# ---------------------------------------------------------------------------
class TestIsValidBucketName:
    def test_valid_examples_from_docstring(self):
        assert vbn.is_valid_bucket_name("bitwarden-logs-123456789012-us-east-1-an")
        assert vbn.is_valid_bucket_name("cloudfront-access-123456789012-eu-west-2-an")

    def test_single_token_prefix(self):
        assert vbn.is_valid_bucket_name("logs-123456789012-ap-southeast-2-an")

    def test_missing_suffix(self):
        assert not vbn.is_valid_bucket_name("bitwarden-123456789012-us-east-1")

    def test_account_id_not_12_digits(self):
        assert not vbn.is_valid_bucket_name("bitwarden-12345-us-east-1-an")

    def test_underscore_in_prefix(self):
        assert not vbn.is_valid_bucket_name(
            "bitwarden_logs-123456789012-us-east-1-an"
        )

    def test_uppercase_rejected(self):
        assert not vbn.is_valid_bucket_name("Bitwarden-123456789012-us-east-1-an")

    def test_plain_name_rejected(self):
        assert not vbn.is_valid_bucket_name("my-bucket")


# ---------------------------------------------------------------------------
# extract_bucket_names_from_file — AST scan of bucket_name= kwargs
# ---------------------------------------------------------------------------
class TestExtractBucketNames:
    def test_extracts_keyword_argument(self, tmp_path):
        src = tmp_path / "stack.py"
        src.write_text(
            textwrap.dedent(
                """
                s3.Bucket(
                    self,
                    "Logs",
                    bucket_name="logs-123456789012-us-east-1-an",
                )
                """
            )
        )
        found = vbn.extract_bucket_names_from_file(src)
        assert [name for _, name in found] == ["logs-123456789012-us-east-1-an"]

    def test_ignores_other_kwargs(self, tmp_path):
        src = tmp_path / "stack.py"
        src.write_text('s3.Bucket(self, "B", versioned=True)\n')
        assert vbn.extract_bucket_names_from_file(src) == []

    def test_syntax_error_returns_empty(self, tmp_path):
        src = tmp_path / "broken.py"
        src.write_text("def (:\n")  # invalid syntax
        assert vbn.extract_bucket_names_from_file(src) == []


# ---------------------------------------------------------------------------
# scan_directory
# ---------------------------------------------------------------------------
class TestScanDirectory:
    def test_flags_invalid_names(self, tmp_path):
        (tmp_path / "good.py").write_text(
            'B(bucket_name="logs-123456789012-us-east-1-an")\n'
        )
        (tmp_path / "bad.py").write_text('B(bucket_name="my-bucket")\n')
        violations, checked = vbn.scan_directory(tmp_path)
        assert checked == 2
        assert len(violations) == 1
        assert violations[0][2] == "my-bucket"

    def test_excludes_vendored_dirs(self, tmp_path):
        venv = tmp_path / ".venv"
        venv.mkdir()
        (venv / "dep.py").write_text('B(bucket_name="my-bucket")\n')
        violations, checked = vbn.scan_directory(tmp_path)
        assert checked == 0
        assert violations == []


# ---------------------------------------------------------------------------
# scan_templates — synthesized CloudFormation
# ---------------------------------------------------------------------------
class TestScanTemplates:
    def _write_template(self, path, bucket_name):
        props = {} if bucket_name is None else {"BucketName": bucket_name}
        path.write_text(
            json.dumps(
                {"Resources": {"Bucket": {"Type": "AWS::S3::Bucket", "Properties": props}}}
            )
        )

    def test_flags_invalid_template_name(self, tmp_path):
        self._write_template(tmp_path / "Stack.template.json", "my-bucket")
        violations, checked = vbn.scan_templates(tmp_path)
        assert checked == 1
        assert len(violations) == 1

    def test_valid_template_name_passes(self, tmp_path):
        self._write_template(
            tmp_path / "Stack.template.json", "logs-123456789012-us-east-1-an"
        )
        violations, checked = vbn.scan_templates(tmp_path)
        assert checked == 1
        assert violations == []

    def test_autogenerated_name_skipped(self, tmp_path):
        # No BucketName property -> auto-named, not checked.
        self._write_template(tmp_path / "Stack.template.json", None)
        violations, checked = vbn.scan_templates(tmp_path)
        assert checked == 0

    def test_intrinsic_bucketname_skipped(self, tmp_path):
        # Non-string BucketName (intrinsic) is skipped.
        (tmp_path / "Stack.template.json").write_text(
            json.dumps(
                {
                    "Resources": {
                        "Bucket": {
                            "Type": "AWS::S3::Bucket",
                            "Properties": {"BucketName": {"Ref": "Param"}},
                        }
                    }
                }
            )
        )
        violations, checked = vbn.scan_templates(tmp_path)
        assert checked == 0

    def test_manifest_and_asset_skipped(self, tmp_path):
        self._write_template(tmp_path / "manifest.json", "my-bucket")
        self._write_template(tmp_path / "asset.abc.template.json", "my-bucket")
        violations, checked = vbn.scan_templates(tmp_path)
        assert checked == 0


# ---------------------------------------------------------------------------
# main — exit codes
# ---------------------------------------------------------------------------
class TestMain:
    def test_exit_zero_when_all_valid(self, tmp_path, monkeypatch, capsys):
        (tmp_path / "good.py").write_text(
            'B(bucket_name="logs-123456789012-us-east-1-an")\n'
        )
        monkeypatch.setattr("sys.argv", ["prog", "--path", str(tmp_path)])
        assert vbn.main() == 0

    def test_exit_one_on_violation(self, tmp_path, monkeypatch):
        (tmp_path / "bad.py").write_text('B(bucket_name="my-bucket")\n')
        monkeypatch.setattr("sys.argv", ["prog", "--path", str(tmp_path)])
        assert vbn.main() == 1

    def test_requires_an_argument(self, monkeypatch):
        import pytest

        monkeypatch.setattr("sys.argv", ["prog"])
        with pytest.raises(SystemExit):
            vbn.main()
